name: Release Grid Trading Plan Calculator

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Run tests
      run: pytest

    - name: Build executable
      run: pyinstaller --onefile grid_trading_app.py

    - name: Get system locale
      run: |
        $locale = (Get-Culture).Name
        Write-Host "##locale=$locale"

    - name: Get version
      id: get_version
      run: |
        $VERSION = (Select-String -Path README.md -Pattern 'Version:' | Select-Object -First 1).Line.Split(':')[1].Trim()
        echo "VERSION=$VERSION" >> $env:GITHUB_ENV
      shell: pwsh

    - name: Compare versions
      id: compare_versions
      run: |
        # Extract current version from README.md
        $current_version = (Select-String -Path README.md -Pattern 'Version:').Matches[0].Groups[1].Value.Trim()
        # Extract major and minor versions only
        $current_major = $current_version.Split('.')[0]
        $current_minor = $current_version.Split('.')[1]

        # Retrieve the latest release tag (if any)
        $latest_tag = git describe --tags $(git rev-list --tags --max-count=1) || $null

        # If there's no previous tag, assume it's a new version
        if (-not $latest_tag) {
          Write-Output "should_release=true" >> $env:GITHUB_ENV
          exit 0
        }

        # Extract major and minor versions from the latest tag
        $latest_major = $latest_tag.Split('.')[0]
        $latest_minor = $latest_tag.Split('.')[1]

        # Check if current version is a minor update only
        if ($current_major -eq $latest_major -and $current_minor -gt $latest_minor) {
          Write-Output "should_release=true" >> $env:GITHUB_ENV
        } else {
          Write-Output "should_release=false" >> $env:GITHUB_ENV
        }
      shell: pwsh

    - name: Create Tag and Release
      id: create_release
      if: env.should_release == 'true'
      uses: actions/github-script@v6
      env:
        VERSION: ${{ env.VERSION }}
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const version = process.env.VERSION;
          
          await github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `refs/tags/v${version}`,
            sha: context.sha
          });
          
          const release = await github.rest.repos.createRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: `v${version}`,
            name: `Grid Trading Plan Calculator v${version}`,
            body: `## 新特性\n${context.payload.head_commit.message}\n\n## 安装说明\n1. 下载附件中的 .exe 文件\n2. 双击运行即可使用，无需安装\n\n如有任何问题或建议，欢迎提交 issue。`,
            draft: false,
            prerelease: false
          });
          
          return release.data.upload_url;

    - name: Upload Release Asset
      uses: actions/github-script@v6
      env:
        VERSION: ${{ env.VERSION }}
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const fs = require('fs').promises;
          const { repo: { owner, repo }, sha } = context;
          const version = process.env.VERSION;
          
          const release = await github.rest.repos.getReleaseByTag({
            owner,
            repo,
            tag: `v${version}`
          }).catch(err => {
            if (err.status === 404) {
              console.log('Release not found, skipping asset upload.');
              return null;
            }
            throw err;
          });

          if (release) {
            console.log('Uploading release asset...');
            const asset = await fs.readFile('./dist/grid_trading_app.exe');
            
            await github.rest.repos.uploadReleaseAsset({
              owner,
              repo,
              release_id: release.data.id,
              name: 'grid_trading_app.exe',
              data: asset
            });
          }
